name: Laravel application (Mysql)

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: "${{ secrets.DOCKER_USER }}/annisadwiwisesa-simple-social-media"
  DOCKER_USER: "${{ secrets.DOCKER_USER }}"

jobs:
  run-mysql-in-docker:
    runs-on: self-hosted
    steps:
      - run: docker rm -f mysql || true
      - run: docker run -d --name mysql -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=social_media -p 3306:3306 mysql:5.7

  build-push-image:
    needs: run-mysql-in-docker
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t $IMAGE_NAME .
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - run: docker push $IMAGE_NAME

  deploy-social-media:
    needs: build-push-image
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: docker-compose down || true
      - run: docker-compose up -d
